### ISSUE TITLE
Ensure routes are explicitly added to network

### ISSUE THREAD

**Issue by balasub** [CASTLEGym/CybORG#3]
In order for the privilege escalation action (#2) to function as expected, each host needs an explicit route to the hosts to which they are connected in the CybORG scenario configuration file. Longer-term, this should be done as part of the Heat template. Short-term, we may need this done as part of the post-installation configuration process.

The current file we are using is here:
https://github.com/cage-challenge/cage-challenge-2/blob/main/CybORG/CybORG/Shared/Scenarios/Scenario1b.yaml

A specific example of a route we need is here: https://github.com/cage-challenge/cage-challenge-2/blob/main/CybORG/CybORG/Shared/Scenarios/Scenario1b.yaml#L341
This example says that User1 should have a route to Enterprise1.

**Comment by hnine999** [comment]
@balasub Afaik, this is complete -- @wehall has tried to place routing information in the HEAT template but it either isn't possible or doesn't work.

Currently, the routing information is placed in the routers post-deployment.

**Comment by balasub** [comment]
Closing as complete.
